src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="restaurant", orphanRemoval=true, cascade={"remove"})
     */
    private $reviews;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->setCreatedAt( new \DateTime() );
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setRestaurant($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->contains($review)) {
            $this->reviews->removeElement($review);
            // set the owning side to null (unless already changed)
            if ($review->getRestaurant() === $this) {
                $review->setRestaurant(null);
            }
        }

        return $this;
    }

    public function getCapitalizeName() : string
    {
        return strtoupper( $this->getName() );
    }

    public function getAverageRating() : ?float
    {
        $reviews = $this->getReviews();
        $reviewsCount = count($reviews);

        if ($reviewsCount < 1) {
            return null;
        }

        $average = 0;
        foreach($reviews as $review) {
            $average += $review->getRating() / $reviewsCount;
        }

        return $average;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\City;
use App\Entity\Restaurant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('city', EntityType::class, [
                'class' => City::class,
                'choice_label' => 'name',
                'attr' => [
                    'class' => 'restaurantFormCitySelect'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Restaurant;
use App\Entity\Review;
use App\Form\RestaurantType;
use App\Form\ReviewType;
use App\Repository\RestaurantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/restaurant")
 */
class RestaurantController extends AbstractController
{
    /**
     * @Route("/", name="restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="restaurant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $restaurant = new Restaurant();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($restaurant);
            $entityManager->flush();

            return $this->redirectToRoute('restaurant_index');
        }

        return $this->render('restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="restaurant_show", methods={"GET", "POST"})
     */
    public function show(Request $request, Restaurant $restaurant): Response
    {
        $review = new Review();
        $review->setRestaurant($restaurant);
        $reviewForm = $this->createForm(ReviewType::class, $review);
        $reviewForm->handleRequest($request);

        if($reviewForm->isSubmitted() && $reviewForm->isValid()) {
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($review);
            $manager->flush();
        }

        return $this->render('restaurant/show.html.twig', [
            'restaurant' => $restaurant,
            'reviewForm' => $reviewForm->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="restaurant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Restaurant $restaurant): Response
    {
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('restaurant_index');
        }

        return $this->render('restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="restaurant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Restaurant $restaurant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($restaurant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('restaurant_index');
    }
}

templates/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('restaurant_delete', {'id': restaurant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary float-right">{{ button_label|default('Créer') }}</button>
{{ form_end(form) }}

templates/restaurant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restaurant{% endblock %}

{% block body %}
    <h1>Edit Restaurant</h1>

    {{ include('restaurant/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

    <a href="{{ path('restaurant_index') }}">back to list</a>

    {{ include('restaurant/_delete_form.html.twig') }}
{% endblock %}

templates/restaurant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant index{% endblock %}

{% block body %}

    <h1>Tous nos restaurants</h1>
    <hr>
    <div class="jumbotron">
        <h2>Le restaurant mis à l'avant cette semaine :</h2>
        <div class="card">
            <div class="card-body">
                <h3>Test</h3>
                <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. A ad architecto assumenda blanditiis commodi eum fuga id illo ipsa minima, natus neque nostrum odit possimus quis repudiandae sed ullam unde?</p>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-sm btn-primary float-right">Voir</a>
            </div>
        </div>
    </div>

    <h2>Liste des restaurants inscrits</h2>

    <table class="table">
        <tbody>
        {% for restaurant in restaurants %}
            <tr>
                <td>
                    <span class="badge badge-success">{{ restaurant.city.name }}</span>
                    <strong>
                        <a href="{{ path('restaurant_show', {'id': restaurant.id}) }}">
                            {{ restaurant.name }}
                        </a>
                    </strong>
                    <br>
                    <small>{{ restaurant.description }}</small>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/restaurant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Restaurant{% endblock %}

{% block body %}
    <h1>Ajouter un établissement</h1>

    {{ include('restaurant/_form.html.twig') }}

    <a href="#">Revenir à votre espace restaurateur</a>
{% endblock %}

{% block javascripts %}
    <script>
        $(document).ready(function() {
            $('.restaurantFormCitySelect').select2();
        });
    </script>
{% endblock %}

{% block stylesheets %}
    <style>
        .select2-container--default {
            color: black;
        }
    </style>
{% endblock %}

templates/restaurant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block body %}
    <a href="{{ path('restaurant_index') }}">< retour à la liste</a>


    <div class="row">
        <div class="col-3">
            <h1>{{ restaurant.capitalizeName }}</h1>
            <h2>
                <span class="badge badge-primary">

                    {% if restaurant.averageRating %}
                        {{ restaurant.averageRating | number_format(2, ',') }}/5
                    {% else %}
                        Pas encore d'avis
                    {% endif%}
                </span>
            </h2>

            <p>
                {{ restaurant.description }}
            </p>
        </div>
        <div class="col-9">
            {% for review in restaurant.reviews %}
                <div class="review mb-2">
                    <h4>{{ review.name }}</h4>
                    <span class="rating">{{ review.rating }}/5</span>
                    <p>{{ review.description }}</p>
                </div>
            {% endfor %}
            <hr>

            <h3>Ajoutez un avis</h3>

            {{ form_start(reviewForm) }}
                {{ form_widget(reviewForm) }}
                <button class="btn btn-primary">Ajouter un avis</button>
            {{ form_end(reviewForm) }}

        </div>
    </div>




{% endblock %}